on: 
  push:
    branches:
      - main
name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Get latest code
      uses: actions/checkout@v4
    
    # Sync files via FTP with retry
    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.TEXTILEDEV_USER }}
        password: ${{ secrets.TEXTILEDEV_PASSWORD }}
        retry_attempts: 3  # Add retry mechanism
